### ISSUE TITLE
Log spam when The One Probe is not installed.

### ISSUE THREAD

**Issue by GirafiStudios** [McJty/McJtyLib#10]
McJtyLib spams the log on world/server join, when "The One Probe" is not installed.
Outtake of the log: https://gist.github.com/GirafiStudios/a6ab0dfa1f3c1c6f8639675104493999

**Comment by McJty** [comment]
That's not McJtyLib doing that. I don't output anything like that. Also notes that it talks about chiseling. Most likelty that's from the Chisel mod
