### ISSUE TITLE
[1.14.2] Errors on loading.

### ISSUE THREAD

**Issue by ProsperCraft** [McJty/McJtyLib#100]
https://gist.github.com/ProsperCraft/a8179aaceede908b2cc0f76303b2d659

forge .63

mcjtylib-1.14-3.5.3-alpha

**Comment by McJty** [comment]
Doesn't seem to have anything to do with McJtyLib?

**Comment by josephcsible** [comment]
I'm not even sure what problem you're trying to show (the big error in there if from Modular Routers). Can you create a fresh instance with just McJtyLib and whatever dependent mod you're using it with, and post a new log from it?

**Comment by ProsperCraft** [comment]
![878d7ee05ba55aaee4d40a02cc11eb05](https://user-images.githubusercontent.com/4427684/60050932-10ed7d00-968f-11e9-9a7b-09061b7914bf.png)

https://gist.github.com/ProsperCraft/feed3f018a46a60415d3ca4fb88d2c06

Only Mcjtylib.

**Comment by ProsperCraft** [comment]
This problem continues when loaded with 1.14.3.  You have to click Proceed to main menu after loading.

**Comment by ProsperCraft** [comment]
This is fixed with the update.
