### ISSUE TITLE
Crashing of minecraft 3.5.4

### ISSUE THREAD

**Issue by fleamclow** [McJty/McJtyLib#101]
yeah basicly it crashes and i think it is because McJtyLib so if anyone could help i would be greatfull
heres the crash report

https://paste.ubuntu.com/p/PFcsjySSbm/

**Comment by josephcsible** [comment]
Please post the full crash report, not just the stack trace from it.

**Comment by McJty** [comment]
It looks as if you're using the wrong version of McJtyLib

**Comment by fleamclow** [comment]
so which one should i use becase im using the newest one taht rf tools requiers

**Comment by McJty** [comment]
If you update McJtyLib then you must also update ALL other mods that are mine (like Deep Resonance, XNet, RFTools Control, ...)

**Comment by fleamclow** [comment]
give me a minute im doing it right now 
also with not enough wands nice and so on

**Comment by McJty** [comment]
yes, those too

**Comment by fleamclow** [comment]
and what site would have newest versions ? curse ?
or 9 minecraft maybe ?

**Comment by McJty** [comment]
Never ever download a mod from any other site then curse! Almost all other sites where you can download mods from are scam sites and very dangerous

**Comment by fleamclow** [comment]
ok i did go as far as to 4th stage in forge but still it crashed

**Comment by McJty** [comment]
Show the log

**Comment by fleamclow** [comment]
https://paste.ubuntu.com/p/NcwXXfyw8r/

**Comment by McJty** [comment]
That is no longer related to my mods. Seems to be in the Comforts mod
