### ISSUE TITLE
Loading issue

### ISSUE THREAD

**Issue by ghost** [McJty/McJtyLib#104]
I have this issue when loading my modpack and it says that it's caused by mcjtylib
[crash-2019-08-28_01.27.10-client.txt](https://github.com/McJtyMods/McJtyLib/files/3548347/crash-2019-08-28_01.27.10-client.txt)

**Comment by josephcsible** [comment]
Looks like a version mismatch. Make sure you're on the latest version of all of McJty's mods, including MeeCreeps.

**Comment by ghost** [comment]
that fixed it!
