### ISSUE TITLE
[1.12.2] My Server is spamming

### ISSUE THREAD

**Issue by SamLam140330** [McJty/McJtyLib#106]
My Server is spamming with this info:
[Server thread/INFO] [mcjtylib_ng]: createStartScanPacket: TileEntity is not a CommandHandler!
Is there any method to solve this problem?

**Comment by McJty** [comment]
I need more info. First, what version of McJtyLib? Also what exactly were you doing ingame?

**Comment by McJty** [comment]
Also the full log might be helpful

**Comment by SamLam140330** [comment]
Thank you for reply.
I am using McJtyLib 1.12-3.5.4.
I am not sure what my friends doing because I am having dinner and not in the server.
This is a part of my server log: https://pastebin.com/bqXkq2WU
*Because I am not a pro account of Pastebin. So I just pasted a part of server log as it has a limit

**Comment by SamLam140330** [comment]
My Server have:

Mods (114): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, A Lib, AE2 Stuff, Actually Additions, Alchemistry, Applied Energistics 2, Aroma1997's Dimensional World, Aroma1997Core, Astral Sorcery, BD Lib, Baubles, Better Builder's Wands, BiblioCraft, Biomes O' Plenty, Blood Magic: Alchemical Wizardry, Bloodmoon, Bonsai Trees, Botania, Brandon's Core, BuildCraft, BuildCraft Builders, BuildCraft Compat, BuildCraft Energy, BuildCraft Factory, BuildCraft Lib, BuildCraft Robotics, BuildCraft Silicon, BuildCraft Transport, CC: Tweaked, CC: Tweaked, Chameleon, Chisel, CoFH Core, CoFH World, CodeChicken Lib, Cooking for Blockheads, Crafting Tweaks, Crossroads, Cucumber Library, Draconic Evolution, Dragon Mounts, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, EnderStorage, Essentials, Extra Utilities 2, Extreme Reactors, FTB Library, Forestry, Forge Microblocks, Forge Multipart CBE, GenDustry, Guide-API, Immersive Engineering, Industrial Foregoing, IndustrialCraft 2, Inventory Tweaks, Iron Backpacks, Iron Chest, LLibrary, Loot Bags, MagicBees, Mantle, McJtyLib, Mekanism, Minecraft Multipart Plugin, Morpheus, Mystical Agradditions, Mystical Agriculture, Open Glider, OpenBlocks, OpenModsLib, OpenModsLib Core, OreExcavation, PortalGun, RFTools, Railcraft, Reborn Core, Redstone Flux, Shadowfacts' Forgelin, SlashBlade, Snad, SpongeForge, Steve's Carts 2, Storage Drawers, Tesla Core Lib, Tesla Core Lib Registries, Thaumcraft, The Twilight Forest, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Tinkers' Construct, YABBA, Zero CORE, iChunUtil, mob_grinding_utils

Plugins (10): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, CatClearLag, LuckPerms, Nucleus, PlaceholderAPI, TabManager, Total Economy

**Comment by Bricklou** [comment]
I have the same problem on my server running on forge 1.12.2 - 14.23.5.2854 with the version 3.5.4.
Is there a way to fix it ?

**Comment by C0D3-M4513R** [comment]
Same problem - Running Project Ozone 3 (Mythic) v3.4.9. It also contains version 3.5.4.

**Comment by McJty** [comment]
I no longer develop on 1.12.2
