### ISSUE TITLE
[1.14.4] Coal generator doesn't consume its coal -> infinite energy

### ISSUE THREAD

**Issue by Draradech** [McJty/McJtyLib#108]
Coal generator doesn't consume its coal -> infinite energy

Versions (clean instance, no other mods present):
Forge: 1.14.4 - 28.1.96
Lib: 1.14-3.5.14-alpha
Base: 1.14-0.0.11-alpha
Power: 1.14-1.2.11-alpha

Reverting only Lib back to 3.5.13 fixes the problem (coal is consumed as expected).

**Comment by McJty** [comment]
I'm about to release a new version of McJtyLib that should hopefully fix this. Let me know if it doesn't (reopen this ticket)
