### ISSUE TITLE
[1.14.4] NullPointerException crash

### ISSUE THREAD

**Issue by DirkSch** [McJty/McJtyLib#109]
I updated from mcjtylib-1.14-3.5.15-alpha to mcjtylib-1.14-3.5.16-alpha and mc crashed.
[latest.log](https://pastebin.com/iFNxUJD1)
[crashreport](https://pastebin.com/U0emcWhF)

**Comment by McJty** [comment]
Did you also update all other mods that depend on McJtyLib? Like RFTools, Restrictions, ...

**Comment by DirkSch** [comment]
yes with all your mods updated the same crash

**Comment by McJty** [comment]
It's crashing in mystical agriculture. Please report to then
