### ISSUE TITLE
Modpack crash with updated mods

### ISSUE THREAD

**Issue by cauliflower69** [McJty/McJtyLib#11]
I have recently started to update our modpack Requiem 1.9.4 on Curse

The issue I have come across is that upon updating your latest set of mods it is crashing a different mod - http://pastebin.com/FzEdWF8S

If I do not update your mods it works fine. - java.lang.IllegalArgumentException: Duplicate id: laser

Sorry if this is in the wrong place.

**Comment by McJty** [comment]
Hmm... I think my mods are doing it right. I guess OpenRadio might be doing something wrong. They should register their tile entity like this:

```
    GameRegistry.registerTileEntityWithAlternatives(tileEntityClass, mod.getModId() + "_" + name, name);
```

Maybe you should report that to them?

**Comment by cauliflower69** [comment]
Thanks again. I have posted the issue https://github.com/XDjackieXD/OpenRadio/issues/12

**Comment by XDjackieXD** [comment]
Issue can be closed as it was clearly my fault (old legacy code back when I had no idea of MC mod coding :P).
(Wouldn't that also mean some other mod also has a tileentity called "laser" without the modid in the id?)

**Comment by Elec332** [comment]
No, because when you use this (addTileWithAlternatives), the id "laser" is added to the nameToClassList, when a tile is registered, it checks wether nameToClassList contains the id, if yes, it throws this exception. (So its not 100% your fault :) )
