### ISSUE TITLE
odd log spam

### ISSUE THREAD

**Issue by border999** [McJty/McJtyLib#113]
https://gist.github.com/border999/82c91b5c1981b7ac8479af775bdcc56b

**Comment by josephcsible** [comment]
Please tell us what you were doing when this happened, and also post more of the log rather than just the part that you think is relevant.

**Comment by border999** [comment]
playing my world as normal. 
[2020-01-31-1.log.gz](https://github.com/McJtyMods/McJtyLib/files/4146832/2020-01-31-1.log.gz)

**Comment by border999** [comment]
I'm also looking into another issue with that world where my game keeps freezing up seconds after loading the overworld. only when I'm in the overworld though, other dimensions work fine.

**Comment by McJty** [comment]
The log seems to point to this:

	at com.Shultrea.Rin.Ench0_4_5.EnchantmentMastery.HandleEnchant(EnchantmentMastery.java:128) ~[EnchantmentMastery.class:?]

So seems enchantmentmastery is messing things up for you.

As to the McJtyLib crash that seems caused by ProjectEx
