### ISSUE TITLE
Divide by zero exception if McJty GUI is open when window is minimized

### ISSUE THREAD

**Issue by Revvilo** [McJty/McJtyLib#114]
I've noticed this one from time to time a while ago and I'm surprised I haven't reported it yet.

Personally, I've encountered this with XNet and RFTools in 1.15, but it's most likely in all of the mods which use McJtyLib to draw the UI.

When in windowed mode, the game will only crash if the game is _minimized_ while a GUI is open, but, in fullscreen mode, simply tabbing out will instantly minimize, and thus crash, the game.
### Crash Report:
https://pastebin.com/3KyUcAfx
### Mod Versions:
- mcjtylib-1.15-4.0.1-alpha
- xnet-1.15-2.0.0-alpha
- rftoolsbase-1.15-1.0.0-alpha
- rftoolsbuilder-1.15-2.0.0-alpha
- rftoolspower-1.15-2.0.1-alpha
- rftoolsstorage-1.15-1.0.1-alpha
- rftoolsutility-1.15-2.0.0-alpha

**Comment by McJty** [comment]
Fixed in the next version
