### ISSUE TITLE
Mod required

### ISSUE THREAD

**Issue by emanuele246gi** [McJty/McJtyLib#116]
What does it mean? I don't understand what the game wants to be installed :(

![Minecraft_ 1 15 2 08_05_2020 13_13_17](https://user-images.githubusercontent.com/61762317/81400809-34e27180-912e-11ea-857e-fd12351ba982.png)

**Comment by McJty** [comment]
There is a problem but I don't understand it myself yet. I'm investigating

**Comment by emanuele246gi** [comment]
Thank you :D

**Comment by McJty** [comment]
Should be fixed now. Update all my mods

**Comment by emanuele246gi** [comment]
Thank you so much :D
