### ISSUE TITLE
Error starting client

### ISSUE THREAD

**Issue by lebanni** [McJty/McJtyLib#118]
forge-1.15.2-31.2.31.jar
mcjtylib-1.15-4.1.2-beta.jar

Mod list in crash log.

[crash-2020-07-12_12.32.29-client.txt](https://github.com/McJtyMods/McJtyLib/files/4908346/crash-2020-07-12_12.32.29-client.txt)

**Comment by McJty** [comment]
Should be fixed now. You have to update XNet and RFTools Base (and possibly other RFTools based mods you might have)
