### ISSUE TITLE
1.15 Beta crashing

### ISSUE THREAD

**Issue by smaynard** [McJty/McJtyLib#119]
Hi 
           I'm trying to use the latest 1.15 Beta versions of the rftools mods  and the lib but it  crashes out. I have a copy of the crash report if you want them.
Alpha versions work fine

**Comment by McJty** [comment]
Of course I need logs. This is way too vague

**Comment by smaynard** [comment]
Where do you want me to put the Crash logs?

**Comment by McJty** [comment]
Upload it to s pastebin or just attach it as a file to this ticket

**Comment by smaynard** [comment]
This is the latest one
I'm probably doing something stupid but I cannot figure it out.
[crash-2020-07-13_10.14.38-client.txt](https://github.com/McJtyMods/McJtyLib/files/5005225/crash-2020-07-13_10.14.38-client.txt)

**Comment by McJty** [comment]
Why are you thinking it's rftools or mcjtylib that's crashing? There is nothing in the log indicating that

**Comment by smaynard** [comment]
It's only when I try to load the new beta version is crashes and when I look at the error log they are the ones with "Ërror"beside them
No problems when I load the alpha versions.

**Comment by smaynard** [comment]
[crash-2020-07-28_07.39.08-client.txt](https://github.com/McJtyMods/McJtyLib/files/5005453/crash-2020-07-28_07.39.08-client.txt)
Sorry loaded the wrong error report

**Comment by McJty** [comment]
You only have the client log. Can you give the server log as well?

**Comment by smaynard** [comment]
No I'm running it on my local not on a server.

**Comment by McJty** [comment]
There is always a server log. Even if you don't play on a server. Anyway from that latest log you uploaded I saw that it is crashing in mekanism. This is not a big in my mods

**Comment by smaynard** [comment]
ok
