### ISSUE TITLE
[1.15.2] Crash after updating from beta

### ISSUE THREAD

**Issue by arp365** [McJty/McJtyLib#120]
I just updated McJtyLib and all RFTTools to the last version and there seems to be a problem with McjtyLib on game start.

```
[12:50:53] [Render thread/ERROR]: Failed to load class mcjty.rftoolsutility.RFToolsUtility
java.lang.NoClassDefFoundError: mcjty/lib/base/ModBase
```

Complete Log : https://pastebin.com/WYUtTQe6

**Comment by McJty** [comment]
Can you give me the version numbers because that error shouldn't be possible with latest. Especially RFTools Utility. What version is that?

**Comment by arp365** [comment]
mcjtylib-1.15-4.1.7
rftoolsbase-1.15-1.1.6
rftoolsbuilder-1.15-2.1.8
rftoolscontrol-1.15-3.0.7
rftoolspower-1.15-2.2.4
rftoolsstorage-1.15-1.1.9
rftoolsutility-1.15-2.1.6
Forge 31.2.36

**Comment by McJty** [comment]
RFToolsUtility - 1.15-2.1.9 is the latest version of RFTools Utility. You're not using latest

**Comment by arp365** [comment]
Now up and running :-)
Thanks, twitch decided to not show me that it was available.
