### ISSUE TITLE
Crash on loading reported as Powah issue

### ISSUE THREAD

**Issue by IamStig** [McJty/McJtyLib#122]
Hi Jorrit, I thought you should see this. It is a crash that reports as Powah's fault but reverting McJitylib and xnet resolved the issue for me.

https://github.com/owmii/Powah/issues/113

Between the 2 of you smart folk I am sure you'll work out where the problem is.

**Comment by McJty** [comment]
I have *no* clue why McJtyLib or XNet could be the cause of this. They don't do anything with particles or whatever. Very weird

**Comment by BedrockLegends** [comment]
@McJty This mods is crashing everyother Mod with Particles, I have had issues with Botania, and much more

**Comment by McJty** [comment]
McJtyLib or XNet don't do anything with particles. There is absolutely no code related to particles in any of my mods

**Comment by BedrockLegends** [comment]
modLoader="javafml"
loaderVersion="[33,)"
license="MIT License https://github.com/McJtyMods/McJtyLib/blob/1.16/LICENCE"
issueTrackerURL="http://github.com/McJtyMods/McJtyLib/issues"
displayURL="http://github.com/McJtyMods/McJtyLib/"
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="McJty"

[[mods]]
modId="mcjtylib"
version="${file.jarVersion}"
displayName="McJtyLib"
#updateJSONURL="http://myurl.me/" #optional
description='''
Base mod for all McJty mods
'''
[[dependencies.mcjtylib]]
    modId="forge"
    mandatory=true
    versionRange="[33,)"
    ordering="NONE"
    side="BOTH"

Your lib is not updated to support 1.16.3
@McJty

**Comment by McJty** [comment]
It is. Why wouldn't it support 1.16.3? I'm developing on 1.16.3. It works fine and people are using it on 1.16.3 (I know because people tell me about it)

**Comment by BedrockLegends** [comment]
[crash-2020-09-30_00.36.45-client.txt](https://github.com/McJtyMods/McJtyLib/files/5303277/crash-2020-09-30_00.36.45-client.txt)
[crash-2020-09-30_00.34.35-client.txt](https://github.com/McJtyMods/McJtyLib/files/5303278/crash-2020-09-30_00.34.35-client.txt)

Boths of these crashes logs came right after I update your Lib

**Comment by McJty** [comment]
Well the crashlog seems to indicate botania. McJtyLib is doing nothing related to those. The fact that it crashes after updating is probably coincidence

**Comment by McJty** [comment]
This also seems to indicate xreliquary is doing something wrong:

java.lang.IllegalStateException: Failed to load description for particle xreliquary:cauldron_steam

	at net.minecraft.client.particle.ParticleManager.func_215236_a(ParticleManager.java:226) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:imm_ptl_mixins.json:client.multiworld_awareness.MixinParticleManager,pl:mixin:A,pl:runtimedistcleaner:A}

	at net.minecraft.client.particle.ParticleManager.lambda$null$0(ParticleManager.java:169) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:imm_ptl_mixins.json:client.multiworld_awareness.MixinParticleManager,pl:mixin:A,pl:runtimedistcleaner:A}

**Comment by BedrockLegends** [comment]
I mean if I use this version mcjtylib-1.16-5.0.6.jar, I have no crashes at all

**Comment by McJty** [comment]
yes you told me. But I have no clue why that would be. That doesn't make sense. In any case, the crashes you got should be reported to xreliquary because it's crashing in their code. No matter if upgrading McJtyLib has an effect or not. The crash happens over there
