### ISSUE TITLE
Log Spam "The mob spawn amounts list for mob minecraft:iron_golem is missing"

### ISSUE THREAD

**Issue by phit** [McJty/McJtyLib#124]
Issue description: 

Hey running All The Mods 6 1.1.5 with mcjtylib-1.16-5.0.10 this is being spammed every tick, leading to enormous log files and making the server console unusable.

```
>.... [20:21:41] [Server thread/ERROR] [mcjtylib/]: The mob spawn amounts list for mob minecraft:iron_golem is missing!
>.... [20:21:41] [Server thread/ERROR] [mcjtylib/]: The mob spawn amounts list for mob minecraft:iron_golem is missing!
>.... [20:21:41] [Server thread/ERROR] [mcjtylib/]: The mob spawn amounts list for mob minecraft:iron_golem is missing!
>.... [20:21:41] [Server thread/ERROR] [mcjtylib/]: The mob spawn amounts list for mob minecraft:iron_golem is missing!
>.... [20:21:41] [Server thread/ERROR] [mcjtylib/]: The mob spawn amounts list for mob minecraft:iron_golem is missing!
```
I was trying to figure out which of your mods is logging this but the Github search and [SourceGraph](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/McJtyMods+The+mob+spawn+amounts+list+type:diff&patternType=literal) wasn't useful.
![image](https://user-images.githubusercontent.com/2097483/96629353-c7a94e00-1313-11eb-8498-35f81b3cf5b2.png)
this was 34min after the last server restart

Steps to reproduce: 

Versions:
* Minecraft: 1.16.3
* Forge: 34.1.23

mcjtylib-1.16-5.0.10.jar
rftoolsutility-1.16-3.0.10.jar
rftoolsbase-1.16-2.0.5.jar
rftoolsbuilder-1.16-3.0.7.jar
rftoolscontrol-1.16-4.0.5.jar
rftoolspower-1.16-3.0.7.jar
rftoolsstorage-1.16-2.0.5.jar

Thanks for looking into this!

**Comment by tomvanswam** [comment]
Same here, identical modpack and versions, only for the minecraft:zombie:
```
[10:33:18] [Server thread/ERROR] [mcjtylib/]: The mob spawn amounts list for mob minecraft:zombie is missing!
[10:33:19] [Server thread/ERROR] [mcjtylib/]: The mob spawn amounts list for mob minecraft:zombie is missing!
... 19x same message at [10:33:19]
[10:33:19] [Server thread/ERROR] [mcjtylib/]: The mob spawn amounts list for mob minecraft:zombie is missing!
[10:33:20] [Server thread/ERROR] [mcjtylib/]: The mob spawn amounts list for mob minecraft:zombie is missing!
```

**Comment by tomvanswam** [comment]
I found this issue on a mod specific github
https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/issues/687
This issue is for a different version mc and thus a different mcjtylib.

Which tells something about a `config/rftools/rftools.cfg` file and add something like:
```
S:"minecraft:zombie.spawnamount.0" <
        I
        minecraft:rotten_flesh
        0
        0.1
     >
    S:"minecraft:zombie.spawnamount.1" <
        B
        minecraft:dirt
        0
        0.2
     >
    S:"minecraft:zombie.spawnamount.2" <
        L
        
        0
        20.0
     >
```
In the all the mods config on the server there is no file that remotely looks like anything mcjty related, so I don't know where to put the code above to try and fix it

**Comment by phit** [comment]
that config sits in `/world/serverconfig/rftoolsutility-mobdata.toml` now as far as I can tell

this also explains where the error comes from https://github.com/McJtyMods/RFToolsUtility/blob/1.16/src/main/java/mcjty/rftoolsutility/modules/spawner/blocks/SpawnerTileEntity.java#L204

**Comment by phit** [comment]
pretty sure I found the issue, the default configs aren't being populated due to a bug in the generation code, I'll submit a PR in a couple minutes to fix the issue

**Comment by phit** [comment]
@tomvanswam thanks for the hint with the config, until this is merged into the mod, you can take [this config](https://gist.github.com/phit/3eee774b170c77895c99d1d9b5b6b9ba#file-new-toml) and replace everything in `/world/serverconfig/rftoolsutility-mobdata.toml` with it

**Comment by McJty** [comment]
Thanks for finding this. I'll release an update soon

**Comment by tomvanswam** [comment]
@phit glad to be of help. I just found out someone did have a RFTools Mobspawner active with a zombie siringe in it. I thought noone had a spawner active on the server.
Thanks for coming up with a fix and a workaround this quick!

**Comment by tomvanswam** [comment]
Side note, the workaround does not appear to work, starting te server overwrites the changed config.
We'll wait patiently until everything gets updated ;-)

**Comment by McJty** [comment]
The update fixing this has been released
