### ISSUE TITLE
Misc crash

### ISSUE THREAD

**Issue by Capt-efficiency** [McJty/McJtyLib#127]
I just had a crash with the modpack im using. I updated to the latest versions of your rftools mods/mcjty library mods.

It said there was a stacktrace error in the crash report, thats why im starting this issue.
I AM using optifine/optiforge, but I tested with those mods deleted from the pack and I still had this issue.

[crash-2020-12-06_11.56.55-fml.txt](https://github.com/McJtyMods/McJtyLib/files/5648351/crash-2020-12-06_11.56.55-fml.txt)

**Comment by McJty** [comment]
Update McJtyLib. You're not using latest
