### ISSUE TITLE
Log Spam "Server thread/ERROR [mcjtylib/]: The mob spawn amounts list for mob minecraft:villager is missing!"

### ISSUE THREAD

**Issue by Paynemacher13** [McJty/McJtyLib#128]
Hey there!
I'm running All the Mods 6 and this error is being spammed on my server console. I followed the thread of the issue posted on Oct. 20. The problem I have is that in the new config created to help said person in that thread, doesn't contain a section for villagers. I am not that well-versed in this stuff. I was just wondering if anybody knew of a fix already that I can access. I have scoured online for almost 24 hours now to no avail. Even if its just a specific line of text I can manually input into my config file. Thank you so much!

![Screenshot 2020-12-29 100248](https://user-images.githubusercontent.com/76746943/103304365-48906000-49bd-11eb-9a38-6307e1d34295.png)

**Comment by McJty** [comment]
Will be fixed in the next version of RFToolsUtility (soon)
