### ISSUE TITLE
[1.10.2] Server Startup Crash

### ISSUE THREAD

**Issue by Kris1432** [McJty/McJtyLib#13]
Version: mcjtylib-1.10-1.9.2.jar
MC Version: 1.10.2
Forge Version: 12.18.0.2004

Log:
http://pastebin.com/5uMek8Ed

Cause: Server starts and causes this crash.

**Comment by dirtyfargo** [comment]
I have the same issue as well

**Comment by Elec332** [comment]
Seems like McJtyLib cannot run on this MC version. (Forge event deleted/moved)

**Comment by McJty** [comment]
Try with mcjtylib-1.10-1.9.4 (i.e the latest)

**Comment by iRmyt** [comment]
Help me

https://pastebin.com/zdFr2cfu

**Comment by McJty** [comment]
You don't have the correct version of mcjtylib. Also please don't use other tickets for different reasons

**Comment by iRmyt** [comment]
what version should I use?

**Comment by McJty** [comment]
Latest.  What are you using?
