### ISSUE TITLE
Infusing Matter(s)

### ISSUE THREAD

**Issue by IamStig** [McJty/McJtyLib#131]
The Matter transmitter and Receiver say they have an infusion bonus, but they can't be placed in an infuser. I placed this here as I am not sure which module has the issue, I can infuse other blocks so??? Edit...Dialing Device also not able to be put in infuser, although I can hopper it in .... to the shard slot
mcjtylib-1.16-5.0.18
rftoolsbase-1.16-2.0.10
rftoolsdim-1.16-7.0.4-beta
rftoolsutility-1.16-3.0.24

**Comment by McJty** [comment]
Will be fixed next release
