### ISSUE TITLE
 java.lang.NoClassDefFoundError: mcjty/lib/varia/FakePlayerGetter

### ISSUE THREAD

**Issue by Nicolasito52** [McJty/McJtyLib#137]
Hello, I was playing minecraft on my locally hosted server with about 70 mods, but when I put the BuilderBlock my game crashed. In the logs I have this error "java.lang.NoClassDefFoundError: mcjty/lib/varia/FakePlayerGetter Did I install one of the mods wrong? Thanks in advance.

the mods used :
(the blue arrows indicate the mods that I suppose are responsible for the crash)
![image](https://user-images.githubusercontent.com/89771045/131305768-8956f0d2-94fc-42d9-9d55-faf344b96470.png)

**Comment by McJty** [comment]
Update McJtyLib

**Comment by Nicolasito52** [comment]
indeed, however when I want to join the world I have again an error:

Error: java.lang.AbstractMethodError: Method mcjty/rftoolsbuilder/modules/builder/blocks/BuilderTileEntity.getBlockPos()Lnet/minecraft/util/math/BlockPos; is abstract

Do I have to remove the block (BuilderBlock) from the world with a software before I connect?

**Comment by McJty** [comment]
Looks like you'll have to update all my mods (rftools*) to latest
