### ISSUE TITLE
[1.10.2] Issues with other mods using the same cofh api

### ISSUE THREAD

**Issue by FiveEYZ** [McJty/McJtyLib#14]
For some reason the cofh api this mod is using isn't complete and is making other mods crash the client when using it.

In this case when using the Configurator from Mekanism that is also using the cofh api
![Img](http://i.imgur.com/Vj4VQ8Q.png)
You can see the size differ between the two IToolHammer.class

here is the crash:
http://pastebin.com/raw/w5eaqJE6

A issue was also made for Mekanism but was closed as it wasn't their fault.
https://github.com/aidancbrady/Mekanism/issues/3474

**Comment by utoc** [comment]
Chiming in on this issue as well; I can confirm that both mods work independent of each other.

Paste here: http://pastebin.com/U0MDpiFY

Specifics: 

rfTools 1.10-5.06
mcJtyLib 1.10-1.9.8
Mekanism 9.1.0.288
FML 1.10.2-12.18.1.2011
on MC 1.10.2

All other mods were removed for testing

The scenario: Place an rfTools timer down, use the handy-dandy smart wrench and right click on a rftools timer in an attempt to rotate it.  The client crashed; the server was unaffected.  I can use EnderIO's Yeta wrench just fine.

For testing, I removed all mods except Deep Resonance, Eleccore, rfTools, mcJtyLib and Mekanism's three mods (tools, generators and the main mod)

**Comment by McJty** [comment]
Was bug in mekanism I think. Has not been an issue for long

**Comment by jamuspsi** [comment]
Hate to be the bearer of bad news, but this is still happening with your latest version installed tonight.  By the sounds of it it's one of my other mods with their many many wrenches.  Is there something I can do to determine which mod is providing cofh so I can get them to update?

(And I don't have mekanism.  I can give you a list of mods, but there's a bunch.)
