### ISSUE TITLE
Payload may not be larger than 2097050 bytes

### ISSUE THREAD

**Issue by ShadowChoas** [McJty/McJtyLib#140]
this is a Minecraft thing. and I don't know how to fix it I have a private server with just me and my relatives I was using ThaumCraft mod and cooking for block heads mod and I used dislocation on a fridge with inventory and crash the server my other relatives can log in just fine but every time I try it auto disconnects  saying "payload may not be larger than 2097050 bytes" which i dont know i have the crash report and don't know how to resolve it.
[crash-2021-09-30_02.27.40-server.txt](https://github.com/McJtyMods/McJtyLib/files/7258962/crash-2021-09-30_02.27.40-server.txt)

**Comment by McJty** [comment]
What has this to do with McJtyLib? You need to report it to the mod author (cookingbook in this case)
