### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by LilJagty** [McJty/McJtyLib#149]
Good afternoon!

I'm having a crash on startup of my 1.18 modpack. The message it gives is KubeJS failed to initialize, but as KubeJS states, that crash was due to a mod not loading correctly on startup. My log.txt has some relevant information- it appears that my build thinks mcjtylib isn't installed but it most certainly is. I tried to reinstall the profile but that didn't fix the problem. I've attached the crash report and latest.log, let me know if you need any more information. 
[crash-2022-01-07_12.16.17-client.txt](https://github.com/McJtyMods/McJtyLib/files/7830307/crash-2022-01-07_12.16.17-client.txt)
[latest.log](https://github.com/McJtyMods/McJtyLib/files/7830309/latest.log)

**Comment by enigmaquip** [comment]
You have the wrong version of mcjtylib

from latest.log
`[12:16:02] [main/INFO]: Found mod file mcjtylib-1.16-5.1.2.jar`

**Comment by LilJagty** [comment]
That was the problem! Looks like Curseforge automatically downloaded the 1.16 version of McJtyLib when I installed the RFTools series on my 1.18 pack. Good catch, thanks for the help.
