### ISSUE TITLE
McJtyLib crashing the forge

### ISSUE THREAD

**Issue by IShline** [McJty/McJtyLib#154]
the library is crashing the forge, i don't know what to do,
Here is the crash report:

---- Minecraft Crash Report ----
// Lolis deobfuscated this stacktrace using MCP's stable-39 mappings.
// Hey, that tickles! Hehehe!

Time: 2023-01-03 21:19:55 BRT
Description: Initializing game

java.lang.NoClassDefFoundError: Lmcjty/rftoolsdim/proxy/CommonProxy;
    at java.lang.Class.getDeclaredFields0(Native Method)
    at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
    at java.lang.Class.getDeclaredField(Class.java:2068)
    at net.minecraftforge.fml.common.ProxyInjector.inject(ProxyInjector.java:70)
    at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:611)
    at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3601)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: mcjty.rftoolsdim.proxy.CommonProxy
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 40 more
Caused by: java.lang.NoClassDefFoundError: mcjty/lib/proxy/AbstractCommonProxy
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 42 more
Caused by: java.lang.ClassNotFoundException: mcjty.lib.proxy.AbstractCommonProxy
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 46 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 772514520 bytes (736 MB) / 1308622848 bytes (1248 MB) up to 2147483648 bytes (2048 MB)
  JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 LoliASM 5.6 Powered by Forge 14.23.5.2859 108 mods loaded, 108 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                                | Version           | Source                                             | Signature                                |
       |:----- |:--------------------------------- |:----------------- |:-------------------------------------------------- |:---------------------------------------- |
       | LC    | minecraft                         | 1.12.2            | minecraft.jar                                      | None                                     |
       | LC    | mcp                               | 9.42              | minecraft.jar                                      | None                                     |
       | LC    | FML                               | 8.0.99.99         | forge-1.12.2-14.23.5.2859.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LC    | forge                             | 14.23.5.2859      | forge-1.12.2-14.23.5.2859.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LC    | micdoodlecore                     | 4.0.4             | minecraft.jar                                      | None                                     |
       | LC    | mixinbooter                       | 7.0               | minecraft.jar                                      | None                                     |
       | LC    | openmodscore                      | 0.12.2            | minecraft.jar                                      | None                                     |
       | LC    | obfuscate                         | 0.4.2             | minecraft.jar                                      | None                                     |
       | LC    | randompatches                     | 1.12.2-1.22.1.10  | randompatches-1.12.2-1.22.1.10.jar                 | None                                     |
       | LC    | techguns_core                     | 1.12.2-1.0        | minecraft.jar                                      | None                                     |
       | LC    | crafttweaker                      | 4.1.19            | CraftTweaker2-1.12-4.1.19.jar                      | None                                     |
       | LC    | endertweaker                      | 1.2.3             | EnderTweaker-1.12.2-1.2.3.jar                      | None                                     |
       | LC    | mtlib                             | 3.0.7             | MTLib-3.0.7.jar                                    | None                                     |
       | LC    | modtweaker                        | 4.0.19            | modtweaker-4.0.20.11.jar                           | None                                     |
       | LC    | jei                               | 4.16.1.301        | jei_1.12.2-4.16.1.301.jar                          | None                                     |
       | LC    | appleskin                         | 1.0.9             | AppleSkin-mc1.12-1.0.9.jar                         | None                                     |
       | LC    | appliedenergistics2               | rv6-stable-7      | appliedenergistics2-rv6-stable-7.jar               | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
       | LC    | quark                             | r1.6-179          | Quark-r1.6-179.jar                                 | None                                     |
       | LC    | autoreglib                        | 1.3-32            | AutoRegLib-1.3-32.jar                              | None                                     |
       | LC    | codechickenlib                    | 3.2.2.353         | CodeChickenLib-1.12.2-3.2.2.353-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LC    | avaritia                          | 3.3.0             | Avaritia-1.12.2-3.3.0.37-universal.jar             | None                                     |
       | LC    | baubles                           | 1.5.2             | Baubles-1.12-1.5.2.jar                             | None                                     |
       | LC    | forgelin                          | 1.8.3             | Forgelin-1.8.3.jar                                 | None                                     |
       | LC    | betterportals                     | 0.3.7.7           | betterportals-0.3.7.7.jar                          | None                                     |
       | LC    | blur                              | 1.0.4-14          | Blur-1.0.4-14.jar                                  | None                                     |
       | LC    | botania                           | r1.10-360         | Botania+r1.10-360.jar                              | None                                     |
       | LC    | redstoneflux                      | 2.1.1             | RedstoneFlux-1.12-2.1.1.1-universal.jar            | None                                     |
       | LC    | brandonscore                      | 2.4.19            | BrandonsCore-1.12.2-2.4.19.214-universal.jar       | None                                     |
       | LC    | loliasm                           | 5.6               | censoredasm5.6.jar                                 | None                                     |
       | LC    | chameleon                         | 1.12-4.1.3        | Chameleon-1.12-4.1.3.jar                           | None                                     |
       | LC    | chickens                          | 6.1.0             | chickens-6.1.0.jar                                 | None                                     |
       | LC    | clumps                            | 3.1.2             | Clumps-3.1.2.jar                                   | None                                     |
       | LC    | cofhcore                          | 4.6.6             | CoFHCore-1.12.2-4.6.6.1-universal.jar              | None                                     |
       | LC    | cofhworld                         | 1.4.0             | CoFHWorld-1.12.2-1.4.0.1-universal.jar             | None                                     |
       | LC    | mantle                            | 1.12-1.3.3.55     | Mantle-1.12-1.3.3.55.jar                           | None                                     |
       | LC    | endercore                         | 1.12.2-0.5.76     | EnderCore-1.12.2-0.5.76.jar                        | None                                     |
       | LC    | enderio                           | 5.3.70            | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
       | LC    | enderiointegrationtic             | 5.3.70            | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
       | LC    | tconstruct                        | 1.12.2-2.13.0.183 | TConstruct-1.12.2-2.13.0.183.jar                   | None                                     |
       | LC    | conarm                            | 1.2.5.10          | conarm-1.12.2-1.2.5.10.jar                         | b33d2c8df492beff56d1bbbc92da49b8ab7345a1 |
       | LC    | ctgui                             | 1.0.0             | CraftTweaker2-1.12-4.1.19.jar                      | None                                     |
       | LC    | crafttweakerjei                   | 2.0.3             | CraftTweaker2-1.12-4.1.19.jar                      | None                                     |
       | LC    | cucumber                          | 1.1.3             | Cucumber-1.12.2-1.1.3.jar                          | None                                     |
       | LC    | draconicevolution                 | 2.3.28            | Draconic-Evolution-1.12.2-2.3.28.354-universal.jar | None                                     |
       | LC    | enderiobase                       | 5.3.70            | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
       | LC    | enderioconduits                   | 5.3.70            | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
       | LC    | enderioconduitsappliedenergistics | 5.3.70            | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
       | LC    | enderioconduitsopencomputers      | 5.3.70            | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
       | LC    | refinedstorage                    | 1.6.16            | refinedstorage-1.6.16.jar                          | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
       | LC    | enderioconduitsrefinedstorage     | 5.3.70            | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
       | LC    | enderiointegrationforestry        | 5.3.70            | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
       | LC    | enderiointegrationticlate         | 5.3.70            | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
       | LC    | enderioinvpanel                   | 5.3.70            | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
       | LC    | ftblib                            | 5.4.7.2           | FTBLib-5.4.7.2.jar                                 | None                                     |
       | LC    | enderiomachines                   | 5.3.70            | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
       | LC    | enderiopowertools                 | 5.3.70            | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
       | LC    | extendedcrafting                  | 1.4.1             | ExtendedCrafting-1.12.2-1.4.1.jar                  | None                                     |
       | LC    | waila                             | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                        | None                                     |
       | LC    | extracells                        | 2.6.7             | ExtraCells-1.12.2-2.6.7.jar                        | None                                     |
       | LC    | galacticraftcore                  | 4.0.4             | Galacticraft-1.12.2-4.0.4.jar                      | None                                     |
       | LC    | galacticraftplanets               | 4.0.4             | Galacticraft-1.12.2-4.0.4.jar                      | None                                     |
       | LC    | mjrlegendslib                     | 1.12.2-1.2.1      | MJRLegendsLib-1.12.2-1.2.1.jar                     | b02331787272ec3515ebe63ecdeea0d746653468 |
       | LC    | extraplanets                      | 1.12.2-0.7.4      | ExtraPlanets-1.12.2-0.7.4.jar                      | b02331787272ec3515ebe63ecdeea0d746653468 |
       | LC    | extrautils2                       | 1.0               | extrautils2-1.12-1.9.9.jar                         | None                                     |
       | LC    | fastfurnace                       | 1.3.1             | FastFurnace-1.12.2-1.3.1.jar                       | None                                     |
       | LC    | fastbench                         | 1.7.4             | FastWorkbench-1.12.2-1.7.4.jar                     | None                                     |
       | LC    | storagedrawers                    | 5.2.2             | StorageDrawers-1.12.2-5.4.2.jar                    | None                                     |
       | LC    | framedcompactdrawers              | 1.2.7             | framedcompactdrawers-1.2.7.jar                     | None                                     |
       | LC    | ftbutilities                      | 5.4.1.131         | FTBUtilities-5.4.1.131.jar                         | None                                     |
       | LC    | ftbbackups                        | 0.0.0.ftbbackups  | FTBUtilitiesBackups-1.0.0.5.jar                    | None                                     |
       | LC    | gravestone                        | 1.10.1            | gravestone-1.10.1.jar                              | None                                     |
       | LC    | llibrary                          | 1.7.20            | llibrary-1.7.20-1.12.2.jar                         | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LC    | iceandfire                        | 1.9.1             | iceandfire-1.9.1-1.12.2.jar                        | None                                     |
       | LC    | ichunutil                         | 7.2.2             | iChunUtil-1.12.2-7.2.2.jar                         | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LC    | inventorypets                     | 2.0.12            | inventorypets-1.12-2.0.12.jar                      | None                                     |
       | LC    | ironchest                         | 1.12.2-7.0.67.844 | ironchest-1.12.2-7.0.72.847.jar                    | None                                     |
       | LC    | jeiutilities                      | 0.2.10            | JEI-Utilities-1.12.2-0.2.10.jar                    | None                                     |
       | LC    | journeymap                        | 1.12.2-5.5.4      | journeymap-1.12.2-5.5.4.jar                        | None                                     |
       | LC    | harvestcraft                      | 1.12.2zb          | Pam's+HarvestCraft+1.12.2zg.jar                    | None                                     |
       | LC    | jehc                              | 1.7.2             | just-enough-harvestcraft-1.12.2-1.7.2.jar          | None                                     |
       | LC    | landlust                          | 1.12.2-0.3.6      | landlust-1.12.2-0.3.6.jar                          | None                                     |
       | LC    | libnine                           | 1.2.1             | libnine-1.12.2-1.2.1.jar                           | None                                     |
       | LC    | threng                            | 1.1.26            | lazy-ae2-1.12.2-1.1.26.jar                         | None                                     |
       | LC    | mcjtylib_ng                       | 3.5.4             | mcjtylib-1.12-3.5.4.jar                            | None                                     |
       | LC    | morechickens                      | 3.1.0             | morechickens-1.12.2-3.1.0.jar                      | None                                     |
       | LC    | morelibs                          | 1.2.2             | morelibs-1.12.2-1.2.2.jar                          | None                                     |
       | LC    | mysticalagriculture               | 1.7.5             | MysticalAgriculture-1.12.2-1.7.5.jar               | None                                     |
       | LC    | mysticalagradditions              | 1.3.2             | MysticalAgradditions-1.12.2-1.3.2.jar              | None                                     |
       | LC    | projecte                          | 1.12.2-PE1.4.1    | ProjectE-1.12.2-PE1.4.1.jar                        | None                                     |
       | LC    | moreplates                        | 5.5.2             | moreplates-1.12.2-5.5.2.jar                        | None                                     |
       | LC    | naturescompass                    | 1.8.5             | NaturesCompass-1.12.2-1.8.5.jar                    | None                                     |
       | LC    | netherbackport                    | 1.0.0             | NetherUpdateBackport-1.12.2(1.0.1).jar             | None                                     |
       | LC    | openmods                          | 0.12.2            | OpenModsLib-1.12.2-0.12.2.jar                      | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | LC    | openblocks                        | 1.8.1             | OpenBlocks-1.12.2-1.8.1.jar                        | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | LC    | portalgun                         | 7.1.0             | PortalGun-1.12.2-7.1.0.jar                         | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LC    | randomthings                      | 4.2.7.4           | RandomThings-MC1.12.2-4.2.7.4.jar                  | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LC    | randomtweaks                      | 1.12.2-2.8.3.1    | randomtweaks-1.12.2-2.8.3.1.jar                    | 20d08fb3fe9c268a63a75d337fb507464c8aaccd |
       | LC    | refinedstorageaddons              | 0.4.5             | refinedstorageaddons-0.4.5.jar                     | None                                     |
       | LC    | rftools                           | 7.73              | rftools-1.12-7.73.jar                              | None                                     |
       | L     | rftoolsdim                        | 5.62              | rftoolsdim-1.12-5.62.jar                           | None                                     |
       | L     | roost                             | 2.0.10            | roost-1.12.2-2.0.10.jar                            | None                                     |
       | L     | simplyjetpacks                    | 1.12.2-2.2.16.1   | SimplyJetpacks2-1.12.2-2.2.16.1.jar                | None                                     |
       | L     | techguns                          | 2.0.2.0           | techguns-1.12.2-2.0.2.0_pre3.2.jar                 | None                                     |
       | L     | tinkersjei                        | 1.2               | tinkersjei-1.2.jar                                 | None                                     |
       | L     | tinkersoredictcache               | 1.0               | TinkersOreDictCache-1.0.jar                        | None                                     |
       | L     | travelersbackpack                 | 1.0.35            | TravelersBackpack-1.12.2-1.0.35.jar                | None                                     |
       | L     | vehicle                           | 0.44.1            | vehicle-mod-0.44.1-1.12.2.jar                      | None                                     |
       | L     | waystones                         | 4.0.72            | Waystones_1.12.2-4.0.72.jar                        | None                                     |
  Loaded coremods (and transformers): LoadingPlugin (RandomThings-MC1.12.2-4.2.7.4.jar)
                                        lumien.randomthings.asm.ClassTransformer
                                      RandomPatches (randompatches-1.12.2-1.22.1.10.jar)
                                        com.therandomlabs.randompatches.core.RPTransformer
                                      LoliASM (censoredasm5.6.jar)
                                        
                                      OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
                                        openmods.core.OpenModsClassTransformer
                                      Quark Plugin (Quark-r1.6-179.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      JeiUtilitiesLoadingPlugin (JEI-Utilities-1.12.2-0.2.10.jar)
                                        com.github.vfyjxf.jeiutilities.asm.JeiUtilitiesClassTransformer
                                      ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
                                        com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
                                      iceandfire (iceandfire-1.9.1-1.12.2.jar)
                                        com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
                                      MicdoodlePlugin (Galacticraft-1.12.2-4.0.4.jar)
                                        micdoodle8.mods.miccore.MicdoodleTransformer
                                      ForgelinPlugin (Forgelin-1.8.3.jar)
                                        
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
                                        com.enderio.core.common.transform.EnderCoreTransformer
                                        com.enderio.core.common.transform.SimpleMixinPatcher
                                      BlurPlugin (Blur-1.0.4-14.jar)
                                        com.tterrag.blur.BlurTransformer
                                      Techguns Core (techguns-1.12.2-2.0.2.0_pre3.2.jar)
                                        techguns.core.TechgunsASMTransformer
                                      MixinBooter (!mixinbooter-7.0.jar)
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 527.37' Renderer: 'NVIDIA GeForce GTX 1650/PCIe/SSE2'
  OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
  AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
  Ender IO: No known problems detected.
            Authlib is : /C:/Users/jaque/AppData/Roaming/.minecraft/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
            
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            !!!You are looking at the diagnostics information, not at the crash.       !!!
            !!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
                                   - wailaIntegration (Enabled/Not Forced)
                                   - quarkIntegration (Enabled/Not Forced)
  Suspected Mods: Forge Mod Loader (FML), Minecraft Forge (forge)
  Launched Version: 1.12.2-forge-14.23.5.2859
  LWJGL: 2.9.4
  OpenGL: NVIDIA GeForce GTX 1650/PCIe/SSE2 GL version 4.6.0 NVIDIA 527.37, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 20x 12th Gen Intel(R) Core(TM) i7-12700KF

**Comment by McJty** [comment]
Your RFToolsDimensions is outdated
