### ISSUE TITLE
Error Loading RFTools Base, Builder and Control.

### ISSUE THREAD

**Issue by Diogo-Rezende** [McJty/McJtyLib#157]
Error in custom Modpack. The error only occurs when I add RFTools and any other related mod.

Error log: 
https://pastebin.pl/view/fde6552a

**Comment by McJty** [comment]
Your mods are outdated. Please use the latest versions (hint, they are for 1.19.2, 1.19.3, and 1.19.4 at the same time but CurseForge doesn't properly show that)
