### ISSUE TITLE
Error with new version (8.0.4)

### ISSUE THREAD

**Issue by wobkobi** [McJty/McJtyLib#164]
![javaw_KACp1dlJoW](https://github.com/McJtyMods/McJtyLib/assets/83639958/10becb9e-4e6f-452e-acdb-6500a839b025)

it was working perfectly fine until the update, now it just crashes 

crash log:
[crash-2024-04-22_18.12.21-fml.txt](https://github.com/McJtyMods/McJtyLib/files/15058412/crash-2024-04-22_18.12.21-fml.txt)

**Comment by McJty** [comment]
Go back to previous version. I removed the last one. There are issues
