### ISSUE TITLE
Shape Card crashes game [1.19.2]

### ISSUE THREAD

**Issue by DexxKnight1** [McJty/McJtyLib#166]
Minecraft version: 1.19.2
McJtyLib version: 1.19-7.2.6
RFTools Base version: 1.19-4.1.8

The Shape Card crash the game by pressing button to change the shape attributes.

![2024-04-26_21 22 54](https://github.com/McJtyMods/McJtyLib/assets/78975662/0c6f8324-1ece-4cdc-9ed6-71be951ebbd7)

[crash-2024-04-26_21.23.03-client.txt](https://github.com/McJtyMods/McJtyLib/files/15134630/crash-2024-04-26_21.23.03-client.txt)

**Comment by McJty** [comment]
I'll check it out

**Comment by McJty** [comment]
I think I fixed it. Can you test? Thanks

**Comment by DexxKnight1** [comment]
It works like a charm, thanks.
