### ISSUE TITLE
[Bug] Server Crash with mcjtylib for 1.21.1 neoforge 

### ISSUE THREAD

**Issue by zuken1997** [McJty/McJtyLib#176]
The Server Crash with the new mcjtylib, Singleplayer is working fine.
[crash-2024-10-21_16.25.25-server.txt](https://github.com/user-attachments/files/17462469/crash-2024-10-21_16.25.25-server.txt)

Versions in use:
McJtyLib 1.21-9.0.2 - Neoforge
RFToolsBase 1.21-6.0.0 - Neoforge
XNet 1.21-7.0.0 - Neoforge

**Comment by McJty** [comment]
Should be fixed with version 9.0.3
