### ISSUE TITLE
Cannot get config value before config is loaded

### ISSUE THREAD

**Issue by whatthedrunk** [McJty/McJtyLib#177]
I have been trying to add the new mods to ATM10 but keep getting this error. 

[crash-2024-10-22_13.25.08-server.txt](https://github.com/user-attachments/files/17480021/crash-2024-10-22_13.25.08-server.txt)

**Comment by McJty** [comment]
This is already fixed in 9.0.4

**Comment by whatthedrunk** [comment]
Thanks, CF kept giving me 9.0.2 for some reason but I clicked refresh and got the correct one this time and it works.
