### ISSUE TITLE
[1.10.2] After minecraft loads

### ISSUE THREAD

**Issue by McReport** [McJty/McJtyLib#18]
After Minecraft load all the mods and etc.. i see the menu and crash I suppose its from your mod?
Crash log:
http://pastebin.com/RgshFe9b

**Comment by canitzp** [comment]
Why are you thinking that the crash is related to mcjty lib. I can't see any references to this mod in the crash report

**Comment by McJty** [comment]
Was going to ask the same thing... The crashlog actually points at forestry
