### ISSUE TITLE
Missing access transformers

### ISSUE THREAD

**Issue by Aaron1011** [McJty/McJtyLib#21]
McJtyLib is currently getting [several access transformer](https://github.com/mezz/JustEnoughItems/blob/1.10/src/main/resources/jei_at.cfg#L4-L5) lines transitively, through its dependency on JustEnoughItems. While this works fine in development, the transformers will not be applied in production is McJtyLib is used with JustEnoughItems.

**Comment by McJty** [comment]
Um, McJtyLib is used massively in production and it works so somehow your theory isn't right. Also McJtyLib has been using guiLeft/guiTop a long time even before JEI was there (from 1.7.10 onwards) so it should be fine. I think the reason it works is that they are protected by default and JEI just makes them public

**Comment by Aaron1011** [comment]
> I think the reason it works is that they are protected by default and JEI just makes them public

That's what I meant - sorry if I wasn't clear. In the unmodified Forge 1.10 sources, those fields have `protocted` access. If McJtyLib isn't run with JEI in production, accessing those fields will produce an `IllegalAccessError`

**Comment by McJty** [comment]
I don't think so as I'm only accessing them in subclasses unless I'm mistaken. Do you have an example of where it access them wrong?

**Comment by Aaron1011** [comment]
[In WindowManager](https://github.com/McJty/McJtyLib/blob/1.10/src/main/java/mcjty/lib/gui/WindowManager.java#L111), you access `guiTop`, `guiLeft`, and `drawHoveringText` from `GuiContainer`. If you setup a plain Forge mod workspace (or recompile your mod without its `deobfCompile` dependencies), you'll see that the fields and methods I mentioned have protected access (but are being accessed from your `WindowManager` class).

**Comment by McJty** [comment]
Fixed in 2.1.2
