### ISSUE TITLE
Bug: PacketUpdateNBTItem

### ISSUE THREAD

**Issue by calvinbalke13** [McJty/McJtyLib#22]
PacketUpdateNBTItem can be used to set NBT on any item, which creates vulnerabilities with other modded items.  It should be restricted so that it can't set NBT on other modded items to make it more secure.

**Comment by McJty** [comment]
Problem is how to detect for which item it is valid and for which it is not?

**Comment by calvinbalke13** [comment]
Yes, that is the problem.

**Comment by mezz** [comment]
(Looking at an example of the packet being [used in RFTools](https://github.com/McJty/RFTools/blob/a1f8aafa24e39f7f75a1216d4119bb58319e376a/src/main/java/mcjty/rftools/items/storage/GuiStorageFilter.java#L91-L96)) I think the safe way to do this is to send a less general packet to the server like "here are the current settings" and have server logic do any updating and checks.
Right now a malicious client mod can send `PacketUpdateNBTItem` to cheat and enchant the held item, for example.

**Comment by McJty** [comment]
Will be solved in the upcoming 2.5.0 McJtyLib
