### ISSUE TITLE
McJtyLib -- Forge does not notice that McJtyLib is on the server/client

### ISSUE THREAD

**Issue by ghost** [McJty/McJtyLib#25]
It doesn't load McJtyLib.. And it gives no error
tested on: forge-1.11-13.19.0.2153 and forge-1.11-13.19.0.2160

**Comment by McJty** [comment]
What? I don't understand this problem?

**Comment by ghost** [comment]
Forge does not show it in Mod Menu when it is in mods folder.
When I want to use it together with rftools rf tools can not find the class. I tryed it on Server and on client. For which forge version it is tested(MC 1.11)

**Comment by McJty** [comment]
McJtyLib is not a mod. It is just a library. So it is normal that it is not in the mod menu. This should be no problem (it never has been a problem) so why do you think it is a problem now?

**Comment by ghost** [comment]
Ok. My Problem is that i think its not loaded because rf tools crashes because it can not find the class.
My crash log: http://pastebin.com/pxu3U5NH

**Comment by McJty** [comment]
Seems that you are missing CompatLayer. Don't forget to add that too

**Comment by ghost** [comment]
Ok I think its it. I will add it when I am back home. I don't have written that i will need this i think there is no message to this in your curse post. Maybe you can add this

**Comment by ghost** [comment]
Thanks for helping me

**Comment by McJty** [comment]
In what post do you mean exactly?

**Comment by Knito58** [comment]
I just updated compatlayer to 0.2.8 and mcjtylib from 2.3.10 to 2.3.11. Forge reports two errors:

RFTools misses mcjtylib_ng 2.3.10 or above ( but its there )
RFTools Control misses mcjtylib_nng 2.3.2 or above. ( hmm... )

I have 2.3.11 which is not recognized.

Going back to mcjtylib version 2.3.10 fixes the issue for the moment.

**Comment by McJty** [comment]
Um, that's weird. This works fine for me. Can you give me your full log?

**Comment by Knito58** [comment]
Haha! "This works for me" is a typical programmer's issue. :)

I renamed 2.3.11.jar.txt back to jar and the 2.3.10.jar back to txt to get the error again. And I cleared all log and crash-report folders. There is no crash-report log! Its in the logs. I put all 3 files together here:

https://www.dropbox.com/s/0iuh6pjtdymzhbq/logs.zip?dl=0

Best of luck in fixing this.

Greetings, Konitor

**Comment by McJty** [comment]
Well it not only works for me but for all the other modpacks where the latest mcjtylib is already being used.

Anyway, can you give me a list of exactly all mods that you were using when that crashed? I can't easily get that info from those logs. I need to know the exact versions of all the mods you're using

**Comment by Knito58** [comment]
Ok. Sorry that I don't use a modpack. Here are my mods in alphabetic order:

ActuallyAdditions-1.11.2-r107.jar
AutoRegLib-1.1-4.jar
backpacks 1.11.2 - 3.1.9.jar
bdlib-1.13.2.7-mc1.11.2.jar
BetterBuildersWands-1.11-0.11.0.233+4d933ac.jar
cfm-4.1.2-mc1.11.2.jar
Chameleon-1.11-3.0.2.jar
compatlayer-1.11.2-0.2.8.jar
CraftingTableIV-1.4.110(1).jar
cxlibrary-1.11.2-1.4.0.jar
dooglamoocitiesmod-1.11.2-1.5.0.jar
ElecCore-1.11-1.7.414.jar
ElevatorMod-1.11.2-1.3.0.jar
extrautils2-1.11.2-1.3.3.jar
FinderCompass-1.11.2.jar
FluxedRedstone-2.6.0.54.jar
forestry_1.11.2-5.3.3.83.jar
gendustry-1.6.5.7-mc1.11.2.jar
generators-0.9.20.5-mc1.11.2.jar
GraveStone Mod 1.7.2.jar
Hopper-Ducts-Mod-1.11.2.jar
Inventory-Tweaks-Mod-1.11.2.jar
ironchest-1.11-7.0.17.799.jar
jei_1.11.2-4.3.3.266.jar
journeymap-1.11.2-5.4.4.jar
justenoughbuttons-1.11-1.3.jar
LLOverlayReloaded-1.1.3-mc1.11.2.jar
malisiscore-1.11.2-5.1.1.jar
malisisdoors-1.11.2-6.1.0.jar
mcjtylib-1.1x-2.3.10.jar
modular-routers-1.11.2-2.1.1.jar
MoreFurnaces-1.11.2-1.9.5.jar
Morph-o-Tool-1.1-13.jar
MultiPageChest-1.11-1.8.0.jar
Natures-Compass-Mod-1.11.2.jar
Neat 1.4-13.jar
OptiFine_1.11.2_HD_U_B8.jar
Overlord-1.11.2-2.3.7.jar
OverpoweredInventory-1.11.2-2.3.0.jar
PetBat-1.11.2.jar
pressure-1.3.1.5-mc1.11.2.jar
Primordial-Crops-Mod-1.11.2.jar
Psi-r1.1-47.jar
Random-Things-Mod-1.11.jar
RebornCore-1.11.2-2.14.2.94-universal.jar
Redstone-Paste-Mod-1.11.2.jar
refinedstorage-1.4.4.jar
rftools-1.1x-6.00.jar
rftoolsctrl-1.1x-1.6.8.jar
RoguelikeDungeons-1.11.2-1.6.5.jar
ShadowMC-1.11.2-3.7.5.jar
SimplyConveyors-2.1.2.jar
SimplyHax-1.11.2.jar
StorageDrawers-1.11.2-4.2.2.jar
supercraftingframe-1.11-1.2.1.89.jar
SuperMiner-[1.11.2]-2.4.32.306.jar
theoneprobe-1.1x-1.4.6.jar
YeOldeTanks-1.11.2-2.0.1.jar

**Comment by McJty** [comment]
But you said it wasn't working with McJtyLib-1.1x-2.3.11 and here you are using the 2.3.10 version?

**Comment by Knito58** [comment]
Yes. The 2.3.10 does work. As soon as I put in the 2.3.11 it stops. This is a listing of what is in the mods folder atm. Sorry, didn't think of putting the 2.3.11 version back. You're correct: 2.3.11 was there when it was not found.

**Comment by McJty** [comment]
Hmm. I'm at a loss. I cannot reproduce this myself and got no other reports so for now I can't help you. I'll keep this open because obviously it is not resolved. Any other clues you might have would be very helpful

**Comment by Knito58** [comment]
Yes I see. I hope version 2.3.12 will become loaded again. TY, greetings.

**Comment by minecraftwar132** [comment]
i need help with this i'm new to mods and i don't know how to put mcjtylib-1.1x-2.3.1 into my libraries can you send me instructions to set up the whole rftools with all the side mods to it

**Comment by McJty** [comment]
I don't understand the question? What's the problem?

**Comment by iRmyt** [comment]
Help me!! Please
https://pastebin.com/kDvrRi69
