### ISSUE TITLE
Crash When Opening RFTools Machines with Moar Signs Toolbox

### ISSUE THREAD

**Issue by Darkosto** [McJty/McJtyLib#29]
Hello,

I'm getting a consistent crash when right clicking on the RFTools Machines with a Moar Signs toolbox being held:

http://pastebin.com/SFssfezp
http://pastebin.com/MhR9hyA5 

McJtyLib: 2.3.4
RFTools: 5.82
RFTools Dimensions: 4.53
MC: 1.10.2
Forge: 2221

Thank you!

**Comment by McJty** [comment]
Seems Moar Signs toolbox doesn't implement a needed method. Did you report to them? Not sure it is their fault though but I would like to hear their feedback
