### ISSUE TITLE
NoClassDefFoundError: mcjty/lib/varia/NullSidedInvWrapper

### ISSUE THREAD

**Issue by NikkyAI** [McJty/McJtyLib#30]
related: McJty/TheOneProbe#138

other crash:  https://gist.github.com/NikkyAI/670b73f511df54358c734b760742050f

minecraft / forge version 1.10.2 - 12.18.3.2185 (recommended)
all mods are the latest version (by FIleDate) from curseforge

the other crash happened when trying to purify resonant liquid, when it enters the bottom tank it crashes the (local) server

**Comment by McJty** [comment]
What version of compatlayer and mcjtylib

**Comment by NikkyAI** [comment]
compatlayer-1.10-0.0.33alpha.jar that seems to explain it.. my fault,
now why the ***** would it load such a old version..

**Comment by NikkyAI** [comment]
the cause was that the files exposed to LatestFiles are one file of each releasetype, which were all marked as not 1.10.2 which forced my script to use the fallback routine i never tested that seems to sort the wrong way
