### ISSUE TITLE
FTB Beyond does not load (1.9)

### ISSUE THREAD

**Issue by Thunder13589** [McJty/McJtyLib#35]
I cannot get ftb to work because it says the compatlayer and mcjtylib are not mod. I understand they are libraries but it does not keep loading after it says this, while on some of my other friends ftb keeps loading after it does not recognize the libraries as mods.  here is the paste bin: https://paste.ubuntu.com/24958288/.
any help would be appreciated.

**Comment by McJty** [comment]
Those are not errors. That's normal as they are not mods. I need to see a full log

**Comment by Thunder13589** [comment]
that is the full log it does not keep going after that

**Comment by McJty** [comment]
Hmm. I can't see what's wrong from those logs but I doubt it has anything to do with compatlayer or McJtyLib
