### ISSUE TITLE
[1.11.2] NullPointerException on opening McJty GUI

### ISSUE THREAD

**Issue by Leo40Git** [McJty/McJtyLib#36]
Version: mcjtylib-1.1x-2.3.11.jar
MC Version: 1.11.2
Forge Version: 13.20.1.2388

Log: [here!](https://github.com/McJty/McJtyLib/files/1117808/crash-2017-07-02_16.30.45-client.txt)

If it matters, the GUI I was trying to open was the RFTools Elevator.

**Comment by McJty** [comment]
What version of compatlayer? Do other gui's work?

**Comment by Leo40Git** [comment]
CompatLayer version is 1.11.2-0.2.9.
I'll test if other GUIs work.

**Comment by Leo40Git** [comment]
Okay, Deep Resonance (version 1.4.8)'s Smelter also causes the crash.
[Crash log, although it's basically the same error.](https://github.com/McJty/McJtyLib/files/1117825/crash-2017-07-02_17.02.47-client.txt)

**Comment by McJty** [comment]
@mezz are you sure nothing changed with jei api on 1.11 as i am getting many reports and my mods haven't changed

**Comment by mezz** [comment]
This particular feature is the same across versions. 
If your gui is open with JEI beside it, it asks "what are the extra areas you are drawing in?" so it can avoid drawing there. For some reason your gui is throwing an exception when asked.

**Comment by McJty** [comment]
I cannot reproduce this with an instance outside dev env with the same versions of jei, mcjtylib, compatlayer, and rftools so I'm out of clues what is going on here. It seems like some other mod is messing up but I wouldn't know how...

**Comment by McJty** [comment]
@mezz upon closer investigations it appears as if my Gui is constructed but your event is called before initGui() of the gui is called. Is that possible? Do I have to protect against that and when can that happen?

**Comment by McJty** [comment]
What modpack is this?

**Comment by Leo40Git** [comment]
I just threw together random mods. No organized modpack.
Also, JEI version is 4.5.0.289, if it matters.

**Comment by McJty** [comment]
I'm releasing a version of McJtyLib that protects against this and will log the error so that we can still try to track down the real problem. Probably a mod that does something wrong in a gui event or something

**Comment by DrGirlfriend** [comment]
I was able to get the same stack trace with mod pack The New Frontier version 29 accessing the DeepResonance smelter UI if that helps anyone

I have not updated any of the contained mods of The Final Frontier
