### ISSUE TITLE
mcjtylib_ng

### ISSUE THREAD

**Issue by 5trgV** [McJty/McJtyLib#38]
I use rftools in a custom Modpack (MC-Version 1.10.2). I have McJtyLib installed but it frequently asks for McJtyLib_ng 2.3.10 or higher on startup. Why is this or where do I get mcjtylib_ng?

Greetz
Felix

**Comment by McJty** [comment]
mcjtylib_ng is just the latest McJtyLib released on curse for 1.10.2/1.11.2 (same release for these two versions of Minecraft)

**Comment by McJty** [comment]
Latest is version 2.4.3 btw

**Comment by 5trgV** [comment]
Thank you for your fas answer I appreciate it.
I will take a closer look this.

**Comment by 5trgV** [comment]
fast*
