### ISSUE TITLE
Um - This is in my log MC-1.12.2 - Forge 512 

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [McJty/McJtyLib#42]
[00:55:00] [main/ERROR] [mcjty.lib.varia.Logging]: Cannot find mob with id 'EntityHorse'!

Isn't that a vanilla mob?

Modlist
https://gist.github.com/P3rf3ctXZer0/accda2ab53b6e089db0e2c9940b4c216

**Comment by McJty** [comment]
Sorry I need a bit more context. Versions for example. What exactly you're doing. A bit more log

**Comment by P3rf3ctXZer0** [comment]
If you check modlist it shows all versions also nothing this is on client startup.

States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version                 | Source                                        | Signature                                |
	|:----- |:-------------------- |:----------------------- |:--------------------------------------------- |:---------------------------------------- |
	| UCHI  | minecraft            | 1.12.2                  | minecraft.jar                                 | None                                     |
	| UCHI  | mcp                  | 9.42                    | minecraft.jar                                 | None                                     |
	| UCHI  | FML                  | 8.0.99.99               | forge-1.12.2-14.23.0.2512-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHI  | forge                | 14.23.0.2512            | forge-1.12.2-14.23.0.2512-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHI  | ivtoolkit            | 1.3.3-1.12              | minecraft.jar                                 | None                                     |
	| UCHI  | jei                  | 4.8.0.108               | jei_1.12.2-4.8.0.108.jar                      | None                                     |
	| UCHI  | abyssalcraft         | 1.9.4-pre-4             | AbyssalCraft-1.12-1.9.4-pre-4.jar             | None                                     |
	| UCHI  | mantle               | 1.12-1.3.1.21           | Mantle-1.12-1.3.1.21.jar                      | None                                     |
	| UCHI  | tconstruct           | 1.12-2.7.3.30           | TConstruct-1.12-2.7.3.30.jar                  | None                                     |
	| UCHI  | acintegration        | 1.6.0                   | AbyssalCraft Integration-1.12.1-1.6.0.jar     | None                                     |
	| UCHI  | craftstudioapi       | 1.0.0                   | CraftStudio-1.0.0.93-mc1.12-alpha.jar         | None                                     |
	| UCHI  | quark                | r1.3-112                | Quark-r1.3-112.jar                            | None                                     |
	| UCHI  | animania             | 1.3.5                   | animania-1.12.2-1.3.5.jar                     | None                                     |
	| UCHI  | architecturecraft    | @VERSION@               | architecturecraft-1.12-1.20.jar               | None                                     |
	| UCHI  | autoreglib           | 1.3-14                  | AutoRegLib-1.3-14.jar                         | None                                     |
	| UCHI  | baubles              | 1.5.1                   | Baubles-1.12-1.5.1.jar                        | None                                     |
	| UCHI  | biomesoplenty        | 7.0.1.2298              | BiomesOPlenty-1.12.2-7.0.1.2298-universal.jar | None                                     |
	| UCHI  | botania              | r1.10-349               | Botania r1.10-349.jar                         | None                                     |
	| UCHI  | infotip              | 1.12.2-1.0              | client-infotooltip-1.12.2-1.0.jar             | None                                     |
	| UCHI  | codechickenlib       | 3.1.3.313               | CodeChickenLib-1.12-3.1.3.313-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHI  | redstoneflux         | 2.0.1                   | RedstoneFlux-1.12-2.0.1.2-universal.jar       | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCHI  | cofhcore             | 4.3.6                   | CoFHCore-1.12-4.3.6.14-universal.jar          | None                                     |
	| UCHI  | cofhworld            | 1.0.1                   | CoFHWorld-1.12-1.0.1.8-universal.jar          | None                                     |
	| UCHI  | cucumber             | 1.0.2                   | cucumber[1.12]-1.0.2.jar                      | None                                     |
	| UCHI  | modcurrency          | 1.12-1.2.6              | Currency-1.12.0-1.2.6.jar                     | None                                     |
	| UCHI  | foamfix              | 0.8.0-1.12              | foamfix-0.8.0-1.12-law.jar                    | None                                     |
	| UCHI  | natura               | 1.12-4.3.0.17           | Natura-1.12-4.3.0.17.jar                      | None                                     |
	| UCHI  | forestry             | 5.6.0.201               | forestry_1.12.2-5.6.0.201.jar                 | None                                     |
	| UCHI  | ftbl                 | 4.1.6                   | FTBLib-4.1.6.jar                              | None                                     |
	| UCHI  | ftbu                 | 4.1.6                   | FTBUtilities-4.1.6.jar                        | None                                     |
	| UCHI  | jeibees              | 0.9.0.5                 | jeibees-0.9.0.5-mc1.12.2.jar                  | None                                     |
	| UCHI  | jeiintegration       | 1.5.0.35                | jeiintegration_1.12.2-1.5.0.35.jar            | None                                     |
	| UCHI  | journeymap           | 1.12.2-5.5.0rc1         | journeymap-1.12.2-5.5.0rc1.jar                | None                                     |
	| UCHI  | lycanitesmobs        | 1.17.2.2 - MC 1.12.2    | LycanitesMobsComplete 1.17.2.2 [1.12.2].jar   | None                                     |
	| UCHI  | arcticmobs           | 1.17.2.2 - MC 1.12.2    | LycanitesMobsComplete 1.17.2.2 [1.12.2].jar   | None                                     |
	| UCHI  | demonmobs            | 1.17.2.2 - MC 1.12.2    | LycanitesMobsComplete 1.17.2.2 [1.12.2].jar   | None                                     |
	| UCHI  | desertmobs           | 1.17.2.2 - MC 1.12.2    | LycanitesMobsComplete 1.17.2.2 [1.12.2].jar   | None                                     |
	| UCHI  | forestmobs           | 1.17.2.2 - MC 1.12.2    | LycanitesMobsComplete 1.17.2.2 [1.12.2].jar   | None                                     |
	| UCHI  | freshwatermobs       | 1.17.2.2 - MC 1.12.2    | LycanitesMobsComplete 1.17.2.2 [1.12.2].jar   | None                                     |
	| UCHI  | infernomobs          | 1.17.2.2 - MC 1.12.2    | LycanitesMobsComplete 1.17.2.2 [1.12.2].jar   | None                                     |
	| UCHI  | junglemobs           | 1.17.2.2 - MC 1.12.2    | LycanitesMobsComplete 1.17.2.2 [1.12.2].jar   | None                                     |
	| UCHI  | mountainmobs         | 1.17.2.2 - MC 1.12.2    | LycanitesMobsComplete 1.17.2.2 [1.12.2].jar   | None                                     |
	| UCHI  | plainsmobs           | 1.17.2.2 - MC 1.12.2    | LycanitesMobsComplete 1.17.2.2 [1.12.2].jar   | None                                     |
	| UCHI  | saltwatermobs        | 1.17.2.2 - MC 1.12.2    | LycanitesMobsComplete 1.17.2.2 [1.12.2].jar   | None                                     |
	| UCHI  | shadowmobs           | 1.17.2.2 - MC 1.12.2    | LycanitesMobsComplete 1.17.2.2 [1.12.2].jar   | None                                     |
	| UCHI  | swampmobs            | 1.17.2.2 - MC 1.12.2    | LycanitesMobsComplete 1.17.2.2 [1.12.2].jar   | None                                     |
	| UCHI  | magicclover          | @VERSION@               | MagicClover-1.0.jar                           | None                                     |
	| UCHI  | metamorph            | 1.1.4                   | metamorph-1.1.4-1.12.1.jar                    | None                                     |
	| UCHI  | mysticalagriculture  | 1.6.5                   | mysticalagriculture-1.12-1.6.5.jar            | None                                     |
	| UCHI  | mysticalagradditions | 1.2.5                   | mysticalagradditions-1.12-1.2.5.jar           | None                                     |
	| UCHI  | harvestcraft         | 1.12.2a                 | Pam's HarvestCraft 1.12.2a.jar                | None                                     |
	| UCHI  | thutcore             | 5.11.3                  | thutcore-5.11.3.jar                           | None                                     |
	| UCHI  | pokecube             | 6.22.3                  | Pokecube_Core-6.22.3.jar                      | None                                     |
	| UCHI  | reccomplex           | 1.4.5                   | RecurrentComplex-1.4.5.1.jar                  | None                                     |
	| UCHI  | theoneprobe          | 1.4.18                  | theoneprobe-1.12-1.4.18.jar                   | None                                     |
	| UCHI  | pokecube_adventures  | 6.12.0                  | Pokecube Revival-6.12.0.jar                   | None                                     |
	| UCHI  | pokecube_mobs        | 4.0.1                   | Pokecube Mobs-4.0.1.jar                       | None                                     |
	| UCHI  | pokecube_moves       | @VERSION@               | Pokecube Mobs-4.0.1.jar                       | None                                     |
	| UCHI  | pokecube_origin      | 4.0.1                   | Pokecube Mobs-4.0.1.jar                       | None                                     |
	| UCHI  | pokecube_compat      | 1.0                     | Pokecube Revival-6.12.0.jar                   | None                                     |
	| UCHI  | pceditmod            | 1.10.2-2.0.0            | Pokecube_Core-6.22.3.jar                      | None                                     |
	| UCHI  | pokecube_ml          | 0.1.0                   | Pokecube_Core-6.22.3.jar                      | None                                     |
	| UCHI  | prefab               | 1.3.0.11                | prefab-1.3.0.11.jar                           | None                                     |
	| UCHI  | reborncore           | 3.4.7.136               | RebornCore-1.12.2-3.4.7.136-universal.jar     | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| UCHI  | redstonearsenal      | 2.3.6                   | RedstoneArsenal-1.12-2.3.6.16-universal.jar   | None                                     |
	| UCHI  | rftools              | 7.00                    | rftools-1.12-7.00.jar                         | None                                     |
	| UCHI  | rftoolsdim           | 5.05                    | rftoolsdim-1.12-5.05.jar                      | None                                     |
	| UCHI  | silentlib            | 2.2.9                   | SilentLib-1.12-2.2.9-89.jar                   | None                                     |
	| UCHI  | scalinghealth        | 1.3.1                   | ScalingHealth-1.12-1.3.1b-76.jar              | None                                     |
	| UCHI  | shetiphiancore       | 3.5.2                   | shetiphiancore-1.12.0-3.5.3.jar               | None                                     |
	| UCHI  | signpic              | 2.8.1                   | SignPicture-1.12.1-2.8.1-universal.jar        | None                                     |
	| UCHI  | silentgems           | 2.5.5                   | SilentsGems-1.12-2.5.5-229.jar                | None                                     |
	| UCHI  | techreborn           | 2.7.8.297               | TechReborn-1.12.2-2.7.8.297-universal.jar     | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| UCHI  | thermalfoundation    | 2.3.6                   | ThermalFoundation-1.12-2.3.6.16-universal.jar | None                                     |
	| UCHI  | thermaldynamics      | 2.3.6                   | ThermalDynamics-1.12-2.3.6.13-universal.jar   | None                                     |
	| UCHI  | tinkertoolleveling   | 1.12-1.0.2b.DEV.1a79301 | TinkerToolLeveling-1.12-1.0.2b.jar            | None                                     |
	| UCHI  | tombmanygraves       | @VERSION@               | TombManyGraves-1.12-4.0.2.jar                 | None                                     |
	| UCHI  | torchmaster          | 1.6.1.53                | torchmaster_1.12.2-1.6.1.53.jar               | 5e9a436b366831c8f54a7e80b015784da69278c6 |
	| UCHI  | treechopper          | 1.2.3                   | TreeChopper-1.12.1-1.2.3.jar                  | None                                     |
	| UCHI  | tumbleweed           | 1.11-0.4.4              | tumbleweed-1.11-0.4.4.jar                     | None                                     |
	| UCHI  | twilightforest       | 3.1.128                 | twilightforest-1.12.2-3.1.128-universal.jar   | None                                     |
	| UCHE  | unifieditems         | 1.7.2.206               | UnifiedItems-1.12.2-1.7.2-206.jar             | None                                     |

**Comment by P3rf3ctXZer0** [comment]
mcjtylib-1.12-2.4.4.jar

**Comment by P3rf3ctXZer0** [comment]
Why doesn't mcjtylib-1.12-2.4.4.jar show up on debug list?

**Comment by McJty** [comment]
It is not a mod
