### ISSUE TITLE
onLoad is wrong place to check for redstone

### ISSUE THREAD

**Issue by McJty** [McJty/McJtyLib#63]
https://github.com/McJty/McJtyLib/commit/2abefe42278a2e0d012fce33f1f54e25d9719dfb

This causes:

http://termbin.com/wpxo

Better is probably to do this the first tick

**Comment by josephcsible** [comment]
So the issue is that addTileEntities calls our code, which calls isBlockIndirectlyGettingPowered, which can cause chunks to load, which will call addTileEntities again, and addTileEntities isn't re-entrant.

**Comment by josephcsible** [comment]
Hmm, is the point of `World.processingLoadedTiles` not to protect from exactly this? Why isn't this used more?
