### ISSUE TITLE
Spam in the server log

### ISSUE THREAD

**Issue by flamechair** [McJty/McJtyLib#64]
Hi,

MC: 1.12.2
Forge: forge-1.12.2-14.23.2.2611-universal
SpongeForge: spongeforge-1.12.2-2611-7.1.0-BETA-2916
mcjtylib-1.12-2.6.3

My server is spammed with several instances of:

`[17:06:39] [Server thread/INFO] [mcjty.lib.varia.Logging]: createStartScanPacket: TileEntity is not a CommandHandler!`

And in rftools.cfg:

`# If true dump a lot of logging information about various things in RFTools. Useful for debugging.
    B:logging=false
`

**Comment by josephcsible** [comment]
Try temporarily removing Sponge and see if it goes away.
