### ISSUE TITLE
Payload may not be larger than 2097050 bytes

### ISSUE THREAD

**Issue by Noobsloth** [McJty/McJtyLib#7]
280 mods loaded in fine.
Add in McJtyLib & create a map. Then this error occurs, you are kicked from single player, and the message "Disconected from server".

http://hastebin.com/xuveqavebo.css

**Comment by McJty** [comment]
I don't see how that can have anything to do with McJtyLib. It doesn't send any packets on its own. The crash also doesn't involve McJtyLib and additionally McMtyLib is used in hundreds of modpacks without any issues.

**Comment by Noobsloth** [comment]
I think we done goofed on a config somewhere then..

**Comment by McJty** [comment]
It could also be that McJtyLib just happens to be the threshold for something and causes something else to fail for that reason. Just guessing

**Comment by Noobsloth** [comment]
That could be. We do have a crap ton of mods in this. xD

**Comment by KaesBuerschtl** [comment]
I know this is somewhat old but commenting in case someone else has this issue. I've run in to this before, for me it's happened whenever any MC data file (player .dat files, level.dat, etc.) gets beyond this size threshold. Check the size of your player data file (Your UUID.dat), it may be past that size and you'll need to delete some NBT entries (check ForgeData\Persistent for any mods adding way too many entries) to resolve it.
