### ISSUE TITLE
[1.12.2] McJtyLib 3.0.0. alpha

### ISSUE THREAD

**Issue by joernott** [McJty/McJtyLib#79]
I just experimented with upgrading my modpack with the 3.0.0 alpha library (and of course RFTools, RFTools Control, RFTools Dimensions and XNet. When opening the inventory of a Crafter, I am getting the attached crash report.
[crash-2018-06-02_17.30.32-client.txt](https://github.com/McJtyMods/McJtyLib/files/2065119/crash-2018-06-02_17.30.32-client.txt)

Maybe this helps by stabilizing this alpha.

**Comment by joernott** [comment]
It is definitely an incompatibility with MouseTweaks (I am using MouseTweaks-2.8-mc1.12.1).

**Comment by McJty** [comment]
We have already fixed the bug for next release
