### ISSUE TITLE
Tier 3 crafter crash

### ISSUE THREAD

**Issue by RexMan04** [McJty/McJtyLib#82]
When I opened up a Tier 3 crafter, my game crashed. Here is what vanilla fix told me to give you. https://paste.dimdev.org/awiyobakus.mccrash

**Comment by McJty** [comment]
I cannot reproduce this. A few questions:

1. Does this happen all the time?
2. Is this also with the tier 2 and tier 1 crafters?
3. Was this with a new crafter that you just made?
