### ISSUE TITLE
McJtyLib 3.0 Crashing Minecraft

### ISSUE THREAD

**Issue by Jordan-Slade** [McJty/McJtyLib#83]
So any version of 3.0 will causing my minecraft to crash with this being the crash report given to me. Why is it I can use any 2.0 version but 3.0 always crashes it and what can be done to fix it?
[crash-2018-06-20_15.07.38-client.txt](https://github.com/McJtyMods/McJtyLib/files/2121111/crash-2018-06-20_15.07.38-client.txt)

**Comment by josephcsible** [comment]
3.0.0 was a breaking release. You need to update all of the mods that use it, such as RFTools.

**Comment by Jordan-Slade** [comment]
I forgot to re-update them I had to back track because before the newest 3.0 version the others weren't working despite being updated I was hoping with the new 3.0 update it would work again. Thanks for that it seems to be working again after updates. XD sorry for the inconvenience.
