### ISSUE TITLE
Crash when picking elevator button color

### ISSUE THREAD

**Issue by KBDeveloper** [McJty/McJtyLib#84]
Just dragging around the color picker when it crashed

https://paste.dimdev.org/eqivekamec.mccrash 

Minecraft 1.12.2 / Forge 14.23.4.2705
McJtyLib 1.12-3.0.1

**Comment by josephcsible** [comment]
Will be fixed in the next release of McJtyLib. In the meantime, you can avoid the crash by making sure you release the mouse button before moving the mouse outside of the color picker area.
