### ISSUE TITLE
[1.12.2] Minecraft Forge Crashes on Phase 2/7

### ISSUE THREAD

**Issue by PulseBeat02** [McJty/McJtyLib#85]
I was building my own modpack for 1.12.2 Minecraft, but my game crashed while loading forge. (Phase 2/7)

It says right after the crash report "_An unexpected issue occurred and the game has crashed. We're sorry for the inconvenience._" Normally, I get an error saying something like _"The game crashed whilst there was a severe problem during mod loading that has caused the game to fail.. etc_", so I don't know what is the problem here.

In Minecraft, it says that Immersivecraft crashed the launcher, but it says in the crash report that McJtyLib is the mod that is causing the problem.

**Here are all of the versions:**

**Immcraft: 1.5.0
Mcjtlib: 3.0.2
Redstone Flux: 2.0.2.3
The One Probe: 1.4.23**

**Minecraft Forge Version: 14.23.4.2726**

**The crash report is here: 

https://pastebin.com/YhZZqKMP**

**Comment by McJty** [comment]
This has been reported before recently but I don't understand why it is happening

**Comment by PulseBeat02** [comment]
Is it a compatibility issue?

**Comment by McJty** [comment]
Not sure yet. We will try to find out

**Comment by PulseBeat02** [comment]
It seems to be a missing folder because when you extract the jar file there is no immcraft folder.

**Comment by josephcsible** [comment]
Two things I notice:

1. All of your jars appear to be unofficial (they have the wrong names). Can you try with official jars?
2. Can you reproduce the error with just ImmersiveCraft and its dependencies installed? If not, what other mod(s) need to be there to cause it?

**Comment by josephcsible** [comment]
Actually, I think I see the real problem: you're using ImmersiveCraft 1.4.1, not 1.5.0 as you said you were. This problem shouldn't occur in 1.5.0.
