### ISSUE TITLE
McJtyLib_ng required even though its installed?

### ISSUE THREAD

**Issue by thederpykrafter** [McJty/McJtyLib#87]
![mcjtylib](https://user-images.githubusercontent.com/25908683/42699778-b7e25dee-868f-11e8-949c-61aef70c1ee7.PNG)
![mcjtylib1](https://user-images.githubusercontent.com/25908683/42699794-c93bd232-868f-11e8-9de5-f5d1a4998ea8.PNG)

**Comment by thederpykrafter** [comment]
should be noted that this error only occurs after updating to 3.0.3 version 3.0.2 works just fine

**Comment by josephcsible** [comment]
I can't reproduce this. Can you post a screenshot of your whole mods folder? Also, can you try uninstalling and reinstalling McJtyLib, MeeCreeps, and RFTools?

**Comment by thederpykrafter** [comment]
![modlist](https://user-images.githubusercontent.com/25908683/42717699-e5d8c2ba-86d0-11e8-87e4-6a0ebd5e8c85.PNG)

forge version 14.23.4.2732
All mods are using default configs
using Twitch launcher(not sure if that's important)

**Comment by josephcsible** [comment]
Still can't reproduce. Can you see if you have the problem in a fresh instance?

**Comment by thederpykrafter** [comment]
[CustomModPack.zip](https://github.com/McJtyMods/McJtyLib/files/2194437/CustomModPack.zip)
Exported configs and mods from Twitch launcher

**Comment by thederpykrafter** [comment]
i duplicated the instance and it seems to be working (takes AGES to launch the pack on my computer :(  ) but it made it past phase 1 whereas before it wouldnt

**Comment by josephcsible** [comment]
If duplicating the instance fixed it, I'd call this a strange glitch with Twitch or your computer, and not anything that we have control over.
