### ISSUE TITLE
Crash on world load with NuclearCraft installed

### ISSUE THREAD

**Issue by tomdodd4598** [McJty/McJtyLib#89]
MC version: 1.12.2
McJtyLib version: 3.0.4
NC Version: 2.11b

[The crashlog](https://pastebin.com/zRdLKYK9) - I could be doing something wrong on my end but I'm not sure. [Here is the TooltipHandler class](https://github.com/turbodiesel4598/NuclearCraft/blob/master/src/main/java/nc/handler/TooltipHandler.java).

**Comment by josephcsible** [comment]
Can you add a statement to print the name of the item that it's crashing on, and let us know which one it is?

**Comment by tomdodd4598** [comment]
Sure thing - I was actually unable to reacreate this myself, so I've sent a modified build to the reporter.

**Comment by antcig** [comment]
https://github.com/turbodiesel4598/NuclearCraft/issues/354
Name of item would be charged porter.

**Comment by tomdodd4598** [comment]
As I am unable to recreate this, I feel there may be another mod involved as the true culprit - I'll start downloading them and see if I find anything.

**Comment by josephcsible** [comment]
Another idea for a custom change to help troubleshoot this: put this at the beginning of the `addRadiationTooltip` method:
```java
if(IRadiationSource.CAPABILITY_RADIATION_SOURCE == null) {
    throw new NullPointerException("IRadiationSource.CAPABILITY_RADIATION_SOURCE is null!");
}
```
 The first parameter to [`getCapability`](https://github.com/MinecraftForge/MinecraftForge/blob/8ace535995522bec0557d4217e0d98b3dc76cf1e/src/main/java/net/minecraftforge/common/capabilities/ICapabilityProvider.java#L68) is annotated `@Nonnull` by Forge, so [our method](https://github.com/McJtyMods/McJtyLib/blob/c22516c6793b3072e80e626e7132dbc041508848/src/main/java/mcjty/lib/varia/ItemCapabilityProvider.java#L41-L49) just assumes it won't be null and will return the "wrong" result if it is (assuming TESLA isn't present, which makes TESLA's capabilities all null), and that particular "wrong" value would cause exactly the crash we're seeing.

**Comment by josephcsible** [comment]
Actually, this could be tested without a custom build. If adding TESLA makes the crash go away, then that's what it is. Then you'd just have to figure out what's making `CAPABILITY_RADIATION_SOURCE` end up being null.

**Comment by tomdodd4598** [comment]
You know what, I was led up the garden path by my own testing there - I've found out why the capability is sometimes null, so I think we can close the issue on this side, as it is not a McJtyLib issue.
Thanks for the help regardless!
