### ISSUE TITLE
Re: #1844 - continuing to crash with RFTools

### ISSUE THREAD

**Issue by thebigschnoz** [McJty/McJtyLib#91]
Same issue as before. rftools is the only mod that seems to be causing this crash. NullPointerException - seems to be related to RFTools and EnderIO

Steps to reproduce: Starting a server

Versions:
- Minecraft: 1.12.2
- Forge: unknown
- McJtyLib: 1.12 - 3.0.5
- RFTools: 1.12 - 7.56 **updated after previous post**

Possibly incompatible mods and versions:

- I'm thinking EnderIO?
- I have the modpack Lapito's Galacticraft 7.2 installed, and this issue only occurred after the update from 7.1.1

[crash-2018-10-10_21.25.09-server.txt](https://github.com/McJtyMods/McJtyLib/files/2466447/crash-2018-10-10_21.25.09-server.txt)

**Comment by josephcsible** [comment]
This is indeed just McJtyMods/RFTools#1844. It's fixed as of commit 7a0f8b4, but a build with this fix hasn't been released yet. The next release of McJtyLib will contain it.
